var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
// This line adds support for controllers and views, enabling the MVC pattern in the application
builder.Services.AddControllersWithViews();

var app = builder.Build();

// Configure the HTTP request pipeline.
// If the application is not in the development environment, configure a default error handler.
if (!app.Environment.IsDevelopment())
{
    // Use a custom error page for handling exceptions.
    app.UseExceptionHandler("/Home/Error");
    // HTTP Strict Transport Security (HSTS) ensures secure connections by enforcing HTTPS.
    app.UseHsts();
}

// Redirect all HTTP requests to HTTPS.
app.UseHttpsRedirection();
// Enable serving static files from the wwwroot folder.
app.UseStaticFiles();

// Enable routing in the application to handle incoming HTTP requests.
app.UseRouting();

// Add authorization middleware to the request pipeline.
// This middleware will check user permissions before allowing access to certain resources.
app.UseAuthorization();

// Define a default route for the application.
// If no specific route is requested, direct the user to the Home controller's Index action.
// The {id?} part is optional, meaning the action can be accessed with or without an id parameter.
app.MapControllerRoute(
    name: "default",
    pattern: "{controller=Home}/{action=Index}/{id?}");

// Start the application and listen for incoming requests.
app.Run();


/*
 * Controller: Ýsteklerin iþlendiði kýsýmdýr. Model ve view arasýndaki akýþý saðlar.
 * Action: Controller'in içinde bulunan metotlardýr. Belirli bir iþlemi gerçekleþtirir.
 * Model: Ýþ mantýðýnýn oluþturulduðu bölümdür. Doðrulama ve veri eriþim iþlemleri de bu bölümde gerçekleþir.
 * View: Kullanýcýya gösterilen sayfadýr. Razor ile oluþturulan HTML çýktýsýný içerir.
 * Razor: C# kodlarýnýn HTML içerisinde yazýlmasýný saðlayan, view dosyalarýnda kullanýlan bir þablon motorudur.
 * Razor View: Razor þablon motoruyla oluþturulmuþ dinamik görünüm dosyalarýdýr.
 * wwwroot: Uygulamanýn CSS, JavaScript, resimler vb. statik dosyalarýn bulunduðu klasördür. Dýþarýya açýk dosyalar burada bulunur.
 * builder.Build(): Uygulamanýn yapýlandýrmalarýný derleyip çallýþma zamaný için hazýr hale getirir.
 * app.Run(): Uygulamayý baþlatýr.
 */

/*
 * Controller: The part where requests are processed. It manages the flow between the model and view.
 * Action: Methods inside the controller. They perform specific operations.
 * Model: The section where business logic is created. Validation and data access operations also occur here.
 * View: The page displayed to the user. It contains the HTML output generated by Razor.
 * Razor: A template engine used in view files that allows writing C# code within HTML.
 * Razor View: Dynamic view files created using the Razor template engine.
 * wwwroot: The folder where the application's static files such as CSS, JavaScript, and images are located. Publicly accessible files are stored here.
 * builder.Build(): Compiles the application's configurations and prepares it for runtime.
 * app.Run(): Starts the application.
 */
